trigger:
- master

pool:
  name: Pool-test
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'CI'
    jobs:
    - job: Dependencias
      displayName: 'Instalacion de dependencias'
      steps:
      - script: |
          echo "Instalacion de dependencias..."
        displayName: 'instalacion la aplicaci√≥n'

    - job: Test
      displayName: 'Pruebas de testeo'
      steps:
      - script: |
          echo "Testeando el codigo..."
        displayName: 'Testeando el codigo'

  - stage: Deploy
    displayName: 'Deploy Stage'
    jobs:
    - job: DeployJob
      displayName: 'Desplegando'
      steps:
      - script: |
          echo "Desplegando la aplicacion..."
        displayName: 'deploy del entorno'